export default [
  {
    id: "1",
    title: "Yogurt Fresa Aflanado",
    price: 4.00,
    offerPrice: 3.00,
    stock: 100,
    img: "granny/fresa_aflanado.png",
    category: "aflanado",
  },
  {
    id: "2",
    title: "Yogurt Maracuya Aflanado",
    price: 4.00,
    offerPrice: 3.00,
    stock: 100,
    img: "granny/maracuya_aflanado.png",
    category: "aflanado",
  },
  {
    id: "3",
    title: "Yogurt Kiwi Aflanado",
    price: 3.00,
    offerPrice: null,
    stock: 100,
    img: "granny/kiwi_aflanado.png",
    category: "aflanado",
  },
  {
    id: "4",
    title: "Yogurt Piña Aflanado",
    price: 3.00,
    offerPrice: null,
    stock: 100,
    img: "granny/pina_aflanado.png",
    category: "aflanado",
  },
  {
    id: "5",
    title: "Yogurt Durazno Aflanado",
    price: 3.00,
    offerPrice: null,
    stock: 100,
    img: "granny/durazno_aflanado.png",
    category: "aflanado",
  },
];
